In [14]:
# Doing all major library imports
import matplotlib.pyplot as plt
import scikitplot as skplt
import numpy as np
import pandas as pd
import seaborn as sns
import scipy.stats as stats
import re

from sklearn import datasets, metrics
from sklearn.linear_model import LinearRegression, LogisticRegression,LogisticRegressionCV 
from sklearn.model_selection import train_test_split, cross_val_score, cross_val_predict, KFold
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.preprocessing import PolynomialFeatures, StandardScaler
from sklearn.linear_model import Ridge, Lasso, ElasticNet, LinearRegression, RidgeCV, LassoCV, ElasticNetCV
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import roc_curve, auc, precision_recall_curve, average_precision_score
from matplotlib.colors import ListedColormap
from sklearn.pipeline import Pipeline, make_pipeline

plt.style.use('fivethirtyeight')

%matplotlib inline
%config InlineBackend.figure_format = 'retina'

import scikitplot as skplt
from matplotlib.colors import ListedColormap
from sklearn.metrics import classification_report, confusion_matrix

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.options.display.float_format = '{:.2f}'.format

import wbdata as wb
import os, glob

In [25]:
un = pd.read_csv ('un_compiled.csv')
un.head()

,Country,Year,Series,Value
0,"Total, all countries or areas",2005,Land area (thousand hectares),13010426.00
1,"Total, all countries or areas",2005,Arable land (thousand hectares),1405868.00
2,"Total, all countries or areas",2005,Permanent crops (thousand hectares),148343.00
3,"Total, all countries or areas",2005,Forest cover (thousand hectares),4032743.00
4,"Total, all countries or areas",2005,Arable land (% of total land area),10.80

In [32]:
cc = {
'Aruba':'ABW',
'Afghanistan':'AFG',
'Africa':'AFR',
'Angola':'AGO',
'Albania':'ALB',
'Andorra':'AND',
'Andean Region':'ANR',
'Arab World':'ARB',
'United Arab Emirates':'ARE',
'Argentina':'ARG',
'Armenia':'ARM',
'American Samoa':'ASM',
'Antigua and Barbuda':'ATG',
'Australia':'AUS',
'Austria':'AUT',
'Azerbaijan':'AZE',
'Burundi':'BDI',
'East Asia & Pacific (IBRD-only countries)':'BEA',
'Europe & Central Asia (IBRD-only countries)':'BEC',
'Belgium':'BEL',
'Benin':'BEN',
'Burkina Faso':'BFA',
'Bangladesh':'BGD',
'Bulgaria':'BGR',
'IBRD countries classified as high income':'BHI',
'Bahrain':'BHR',
'Bahamas, The':'BHS',
'Bosnia and Herzegovina':'BIH',
'Latin America & the Caribbean (IBRD-only countries)':'BLA',
'Belarus':'BLR',
'Belize':'BLZ',
'Middle East & North Africa (IBRD-only countries)':'BMN',
'Bermuda':'BMU',
'Bolivia':'BOL',
'Brazil':'BRA',
'Barbados':'BRB',
'Brunei Darussalam':'BRN',
'Sub-Saharan Africa (IBRD-only countries)':'BSS',
'Bhutan':'BTN',
'Botswana':'BWA',
'Sub-Saharan Africa (IFC classification)':'CAA',
'Central African Republic':'CAF',
'Canada':'CAN',
'East Asia and the Pacific (IFC classification)':'CEA',
'Central Europe and the Baltics':'CEB',
'Europe and Central Asia (IFC classification)':'CEU',
'Switzerland':'CHE',
'Channel Islands':'CHI',
'Chile':'CHL',
'China':'CHN',
'Cote d\'Ivoire':'CIV',
'Latin America and the Caribbean (IFC classification)':'CLA',
'Middle East and North Africa (IFC classification)':'CME',
'Cameroon':'CMR',
'Congo, Dem. Rep.':'COD',
'Congo, Rep.':'COG',
'Colombia':'COL',
'Comoros':'COM',
'Cabo Verde':'CPV',
'Costa Rica':'CRI',
'South Asia (IFC classification)':'CSA',
'Caribbean small states':'CSS',
'Cuba':'CUB',
'Curacao':'CUW',
'Cayman Islands':'CYM',
'Cyprus':'CYP',
'Czech Republic':'CZE',
'East Asia & Pacific (IDA-eligible countries)':'DEA',
'Europe & Central Asia (IDA-eligible countries)':'DEC',
'Germany':'DEU',
'IDA countries classified as Fragile Situations':'DFS',
'Djibouti':'DJI',
'Latin America & the Caribbean (IDA-eligible countries)':'DLA',
'Dominica':'DMA',
'Middle East & North Africa (IDA-eligible countries)':'DMN',
'IDA countries not classified as Fragile Situations':'DNF',
'Denmark':'DNK',
'IDA countries in Sub-Saharan Africa not classified as fragile situations ':'DNS',
'Dominican Republic':'DOM',
'South Asia (IDA-eligible countries)':'DSA',
'IDA countries in Sub-Saharan Africa classified as fragile situations ':'DSF',
'Sub-Saharan Africa (IDA-eligible countries)':'DSS',
'IDA total, excluding Sub-Saharan Africa':'DXS',
'Algeria':'DZA',
'East Asia & Pacific (excluding high income)':'EAP',
'Early-demographic dividend':'EAR',
'East Asia & Pacific':'EAS',
'Europe & Central Asia (excluding high income)':'ECA',
'Europe & Central Asia':'ECS',
'Ecuador':'ECU',
'Egypt, Arab Rep.':'EGY',
'Euro area':'EMU',
'Eritrea':'ERI',
'Spain':'ESP',
'Estonia':'EST',
'Ethiopia':'ETH',
'European Union':'EUU',
'Fragile and conflict affected situations':'FCS',
'Finland':'FIN',
'Fiji':'FJI',
'France':'FRA',
'Faroe Islands':'FRO',
'Micronesia, Fed. Sts.':'FSM',
'IDA countries classified as fragile situations, excluding Sub-Saharan Africa':'FXS',
'Gabon':'GAB',
'United Kingdom':'GBR',
'Georgia':'GEO',
'Ghana':'GHA',
'Gibraltar':'GIB',
'Guinea':'GIN',
'Gambia, The':'GMB',
'Guinea-Bissau':'GNB',
'Equatorial Guinea':'GNQ',
'Greece':'GRC',
'Grenada':'GRD',
'Greenland':'GRL',
'Guatemala':'GTM',
'Guam':'GUM',
'Guyana':'GUY',
'High income':'HIC',
'Hong Kong SAR, China':'HKG',
'Honduras':'HND',
'Heavily indebted poor countries (HIPC)':'HPC',
'Croatia':'HRV',
'Haiti':'HTI',
'Hungary':'HUN',
'IBRD, including blend':'IBB',
'IBRD only':'IBD',
'IDA & IBRD total':'IBT',
'IDA total':'IDA',
'IDA blend':'IDB',
'Indonesia':'IDN',
'IDA only':'IDX',
'Isle of Man':'IMN',
'India':'IND',
'Not classified':'INX',
'Ireland':'IRL',
'Iran, Islamic Rep.':'IRN',
'Iraq':'IRQ',
'Iceland':'ISL',
'Israel':'ISR',
'Italy':'ITA',
'Jamaica':'JAM',
'Jordan':'JOR',
'Japan':'JPN',
'Kazakhstan':'KAZ',
'Kenya':'KEN',
'Kyrgyz Republic':'KGZ',
'Cambodia':'KHM',
'Kiribati':'KIR',
'St. Kitts and Nevis':'KNA',
'Korea, Rep.':'KOR',
'Kuwait':'KWT',
'Latin America & Caribbean (excluding high income)':'LAC',
'Lao PDR':'LAO',
'Lebanon':'LBN',
'Liberia':'LBR',
'Libya':'LBY',
'St. Lucia':'LCA',
'Latin America & Caribbean ':'LCN',
'Latin America and the Caribbean':'LCR',
'Least developed countries: UN classification':'LDC',
'Low income':'LIC',
'Liechtenstein':'LIE',
'Sri Lanka':'LKA',
'Lower middle income':'LMC',
'Low & middle income':'LMY',
'Lesotho':'LSO',
'Late-demographic dividend':'LTE',
'Lithuania':'LTU',
'Luxembourg':'LUX',
'Latvia':'LVA',
'Macao SAR, China':'MAC',
'St. Martin (French part)':'MAF',
'Morocco':'MAR',
'Central America':'MCA',
'Monaco':'MCO',
'Moldova':'MDA',
'Middle East (developing only)':'MDE',
'Madagascar':'MDG',
'Maldives':'MDV',
'Middle East & North Africa':'MEA',
'Mexico':'MEX',
'Marshall Islands':'MHL',
'Middle income':'MIC',
'North Macedonia':'MKD',
'Mali':'MLI',
'Malta':'MLT',
'Myanmar':'MMR',
'Middle East & North Africa (excluding high income)':'MNA',
'Montenegro':'MNE',
'Mongolia':'MNG',
'Northern Mariana Islands':'MNP',
'Mozambique':'MOZ',
'Mauritania':'MRT',
'Mauritius':'MUS',
'Malawi':'MWI',
'Malaysia':'MYS',
'North America':'NAC',
'North Africa':'NAF',
'Namibia':'NAM',
'New Caledonia':'NCL',
'Niger':'NER',
'Nigeria':'NGA',
'Nicaragua':'NIC',
'Netherlands':'NLD',
'Non-resource rich Sub-Saharan Africa countries, of which landlocked':'NLS',
'Norway':'NOR',
'Nepal':'NPL',
'Non-resource rich Sub-Saharan Africa countries':'NRS',
'Nauru':'NRU',
'IDA countries not classified as fragile situations, excluding Sub-Saharan Africa':'NXS',
'New Zealand':'NZL',
'OECD members':'OED',
'Oman':'OMN',
'Other small states':'OSS',
'Pakistan':'PAK',
'Panama':'PAN',
'Peru':'PER',
'Philippines':'PHL',
'Palau':'PLW',
'Papua New Guinea':'PNG',
'Poland':'POL',
'Pre-demographic dividend':'PRE',
'Puerto Rico':'PRI',
'Korea, Dem. People???s Rep.':'PRK',
'Portugal':'PRT',
'Paraguay':'PRY',
'West Bank and Gaza':'PSE',
'Pacific island small states':'PSS',
'Post-demographic dividend':'PST',
'French Polynesia':'PYF',
'Qatar':'QAT',
'Romania':'ROU',
'Resource rich Sub-Saharan Africa countries':'RRS',
'Resource rich Sub-Saharan Africa countries, of which oil exporters':'RSO',
'Russian Federation':'RUS',
'Rwanda':'RWA',
'South Asia':'SAS',
'Saudi Arabia':'SAU',
'Southern Cone':'SCE',
'Sudan':'SDN',
'Senegal':'SEN',
'Singapore':'SGP',
'Solomon Islands':'SLB',
'Sierra Leone':'SLE',
'El Salvador':'SLV',
'San Marino':'SMR',
'Somalia':'SOM',
'Serbia':'SRB',
'Sub-Saharan Africa (excluding high income)':'SSA',
'South Sudan':'SSD',
'Sub-Saharan Africa ':'SSF',
'Small states':'SST',
'Sao Tome and Principe':'STP',
'Suriname':'SUR',
'Slovak Republic':'SVK',
'Slovenia':'SVN',
'Sweden':'SWE',
'Eswatini':'SWZ',
'Sint Maarten (Dutch part)':'SXM',
'Sub-Saharan Africa excluding South Africa':'SXZ',
'Seychelles':'SYC',
'Syrian Arab Republic':'SYR',
'Turks and Caicos Islands':'TCA',
'Chad':'TCD',
'East Asia & Pacific (IDA & IBRD countries)':'TEA',
'Europe & Central Asia (IDA & IBRD countries)':'TEC',
'Togo':'TGO',
'Thailand':'THA',
'Tajikistan':'TJK',
'Turkmenistan':'TKM',
'Latin America & the Caribbean (IDA & IBRD countries)':'TLA',
'Timor-Leste':'TLS',
'Middle East & North Africa (IDA & IBRD countries)':'TMN',
'Tonga':'TON',
'South Asia (IDA & IBRD)':'TSA',
'Sub-Saharan Africa (IDA & IBRD countries)':'TSS',
'Trinidad and Tobago':'TTO',
'Tunisia':'TUN',
'Turkey':'TUR',
'Tuvalu':'TUV',
'Taiwan, China':'TWN',
'Tanzania':'TZA',
'Uganda':'UGA',
'Ukraine':'UKR',
'Upper middle income':'UMC',
'Uruguay':'URY',
'United States':'USA',
'Uzbekistan':'UZB',
'St. Vincent and the Grenadines':'VCT',
'Venezuela, RB':'VEN',
'British Virgin Islands':'VGB',
'Virgin Islands (U.S.)':'VIR',
'Vietnam':'VNM',
'Vanuatu':'VUT',
'World':'WLD',
'Samoa':'WSM',
'Kosovo':'XKX',
'Sub-Saharan Africa excluding South Africa and Nigeria':'XZN',
'Yemen, Rep.':'YEM',
'South Africa':'ZAF',
'Zambia':'ZMB',
'Zimbabwe':'ZWE',
    
    'Afghanistan, Islamic Republic of': 'AFG', 
    #'Anguilla',
    'Armenia, Republic of': 'ARM', 
    'Azerbaijan, Republic of': 'AZE',
    'Bahrain, Kingdom of': 'BHR', 
    'China, P.R.: Hong Kong' : 'HKG',
    'China, P.R.: Macao': 'MAC', 
    'China, P.R.: Mainland': 'CHN',
    'Congo, Democratic Republic of' : 'COD', 
    'Congo, Republic of': 'COG',
    "Côte d'Ivoire": 'CIV', 
    'Egypt': 'EGY', 
    #'Eswatini, Kingdom of',
    'Iran, Islamic Republic of':'IRN', 
    'Korea, Republic of': 'KOR',
    #'Kosovo, Republic of', 
    "Lao People's Democratic Republic" : 'LAO',
    #'Marshall Islands, Republic of', 
    #'Micronesia, Federated States of',
    #'Montserrat', 
    'North Macedonia, Republic of':'MKD',
    'Serbia, Republic of': 'SRB', 
    'São Tomé and Príncipe': 'STP',
    'Timor-Leste, Dem. Rep. of': 'TLS', 
    'Yemen, Republic of': 'YEM',
    
    
    'Bosnia & Herzegovina':'BIH', 
    'Gambia':'GMB', 
    'Iran':'IRN', 
    #'North Korea': ,
    'Trinidad & Tobago' : 'TTO', 
    'Venezuela' : 'VEN', 
    'Viet Nam': 'VNM', 
    'Yemen': 'YEM',
    
     'Bolivia (Plurinational State of)':'BOL',
"Dem. People's Rep. Korea":'KOR',
"Lao People's Dem. Rep.":'LAO',
'Bahamas':'BHS',
'Bolivia (Plurin. State of)':'BOL',
'China':'CHN',
'Congo':'COG',
'Dem. Rep. of the Congo':'COD',
'Hong Kong SAR':'HKG',
'Iran (Islamic Rep. of)':'IRN',
'Iran (Islamic Republic of)':'IRN',
'Kyrgyzstan':'KGZ',
'Netherlands Antilles [former]':'NLD',
'Republic of Moldova':'MDA',
'Serbia and Monten. [former]':'SRB',
'Slovakia':'SVK',
'Sudan [former]':'SDN',
'TFYR of Macedonia':'MKD',
'U.S. Minor Outlying islands':'USA',
'United Rep. of Tanzania':'TZA',
'United States of America':'USA',
'United States Virgin Islands':'VIR',
'Venezuela (Boliv. Rep. of)':'VEN',

    
}

In [33]:
un['country_code'] = un.Country.replace (cc)
un.head()

,Country,Year,Series,Value,country_code
0,"Total, all countries or areas",2005,Land area (thousand hectares),13010426.00,"Total, all countries or areas"
1,"Total, all countries or areas",2005,Arable land (thousand hectares),1405868.00,"Total, all countries or areas"
2,"Total, all countries or areas",2005,Permanent crops (thousand hectares),148343.00,"Total, all countries or areas"
3,"Total, all countries or areas",2005,Forest cover (thousand hectares),4032743.00,"Total, all countries or areas"
4,"Total, all countries or areas",2005,Arable land (% of total land area),10.80,"Total, all countries or areas"

In [34]:
un[un.Country == un.country_code].Country.unique()

array(['Total, all countries or areas', 'Northern Africa',
       'Sub-Saharan Africa', 'Eastern Africa', 'Middle Africa',
       'Southern Africa', 'Western Africa', 'Americas',
       'Northern America', 'Latin America & the Caribbean', 'Caribbean',
       'South America', 'Asia', 'Central Asia', 'Eastern Asia',
       'South-eastern Asia', 'Southern Asia', 'Western Asia', 'Europe',
       'Eastern Europe', 'Northern Europe', 'Southern Europe',
       'Western Europe', 'Oceania', 'Australia and New Zealand',
       'Melanesia', 'Micronesia', 'Polynesia', 'Antarctica', 'Anguilla',
       'Bonaire, St. Eustatius & Saba', 'British Indian Ocean Terr.',
       'China, Hong Kong SAR', 'China, Macao SAR', 'Christmas Island',
       'Cook Islands', 'Côte d’Ivoire', 'Curaçao', 'Czechia',
       'Falkland Islands (Malvinas)', 'French Guiana',
       'French Southern Territories', 'Guadeloupe',
       'Heard Is. and McDonald Is.', 'Martinique', 'Mayotte',
       'Micronesia (Fed. States of)', 'Montserrat', 'Niue',
       'Norfolk Island', 'Other non-specified areas', 'Pitcairn',
       'Republic of Korea', 'Réunion', 'Saint Barthélemy', 'Saint Helena',
       'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Martin (French part)', 'Saint Pierre and Miquelon',
       'Saint Vincent & Grenadines', 'South Georgia & Sandwich Is.',
       'State of Palestine', 'Svalbard and Jan Mayen Is.', 'Tokelau',
       'Wallis and Futuna Islands', 'Western Sahara', 'Latin America',
       'South-central Asia', 'Guernsey', 'Jersey', 'Ascension', 'Bonaire',
       'Sint Eustatius', 'Saba', 'Eastern and South-Eastern Asia',
       'Areas not specified', 'Åland Islands', 'Holy See',
       'Northern Africa and Western Asia', 'Northern America and Europe',
       'OAPI', 'ARIPO', 'EAPO', 'EPO', 'GCC', 'Central African Rep.',
       'Swaziland', 'European Union (EU)'], dtype=object)

In [35]:
un_ah = pd.pivot_table (un, index =['Country', 'country_code', 'Year'], columns = 'Series', values = 'Value', aggfunc=np.sum) 
un_ah.head()

Series                     Agricultural production (Index Base: 2004-2006 = 100)  \
Country country_code Year
ARIPO   ARIPO        1985                                                nan
                     1995                                                nan
                     2005                                                nan
                     2010                                                nan
                     2014                                                nan

Series                     All staff compensation as % of total expenditure in public institutions (%)  \
Country country_code Year
ARIPO   ARIPO        1985                                                nan
                     1995                                                nan
                     2005                                                nan
                     2010                                                nan
                     2014                                                nan

Series                     Arable land (% of total land area)  \
Country country_code Year
ARIPO   ARIPO        1985                                 nan
                     1995                                 nan
                     2005                                 nan
                     2010                                 nan
                     2014                                 nan

Series                     Arable land (thousand hectares)  \
Country country_code Year
ARIPO   ARIPO        1985                              nan
                     1995                              nan
                     2005                              nan
                     2010                              nan
                     2014                              nan

Series                     Assault rate per 100,000 population  \
Country country_code Year
ARIPO   ARIPO        1985                                  nan
                     1995                                  nan
                     2005                                  nan
                     2010                                  nan
                     2014                                  nan

Series                     Asylum seekers, including pending cases (number)  \
Country country_code Year
ARIPO   ARIPO        1985                                               nan
                     1995                                               nan
                     2005                                               nan
                     2010                                               nan
                     2014                                               nan

Series                     Capital expenditure as % of total expenditure in public institutions (%)  \
Country country_code Year
ARIPO   ARIPO        1985                                                nan
                     1995                                                nan
                     2005                                                nan
                     2010                                                nan
                     2014                                                nan

Series                     Changes in stocks (petajoules)  \
Country country_code Year
ARIPO   ARIPO        1985                             nan
                     1995                             nan
                     2005                             nan
                     2010                             nan
                     2014                             nan

Series                     Consumer price index: Food  \
Country country_code Year
ARIPO   ARIPO        1985                         nan
                     1995                         nan
                     2005                         nan
                     2010                         nan
                     2014                         nan

Series                     Consumer price index: General  \
Country country_code Year
ARIPO   ARIPO        1985                            nan
                     1995                            nan
                     2005                            nan
                     2010                            nan
                     2014                            nan

Series                     Current expenditure other than staff compensation as % of total expenditure in public institutions (%)  \
Country country_code Year
ARIPO   ARIPO        1985                                                nan
                     1995                                                nan
                     2005                                                nan
                     2010                                                nan
                     2014                                                nan

Series                     Current health expenditure (% of GDP)  \
Country country_code Year
ARIPO   ARIPO        1985                                    nan
                     1995                                    nan
                     2005                                    nan
                     2010                                    nan
                     2014                                    nan

Series                     Domestic general government health expenditure (% of total government expenditure)  \
Country country_code Year
ARIPO   ARIPO        1985                                                nan
                     1995                                                nan
                     2005                                                nan
                     2010                                                nan
                     2014                                                nan

Series                     Emissions (thousand metric tons of carbon dioxide)  \
Country country_code Year
ARIPO   ARIPO        1985                                                nan
                     1995                                                nan
                     2005                                                nan
                     2010                                                nan
                     2014                                                nan

Series                     Emissions per capita (metric tons of carbon dioxide)  \
Country country_code Year
ARIPO   ARIPO        1985                                                nan
                     1995                                                nan
                     2005                                                nan
                     2010                                                nan
                     2014                                                nan

Series                     Expenditure by level of education: pre-primary (as % of government expenditure)  \
Country country_code Year
ARIPO   ARIPO        1985                                                nan
                     1995                                                nan
                     2005                                                nan
                     2010                                                nan
                     2014                                                nan

Series                     Expenditure by level of education: primary (as % of government expenditure)  \
Country country_code Year
ARIPO   ARIPO        1985                                                nan
                     1995                                                nan
                     2005                                                nan
                     2010                                                nan
                     2014                                                nan

Series                     Expenditure by level of education: secondary (as % of government expenditure)  \
Country country_code Year
ARIPO   ARIPO        1985                                                nan
                     1995                                                nan
                     2005                                                nan
                     2010                                                nan
                     2014                                                nan

Series                     Expenditure by level of education: tertiary (as % of government expenditure)  \
Country country_code Year
ARIPO   ARIPO        1985                                                nan
                     1995                                                nan
                     2005                                                nan
                     2010                                                nan
                     2014                                                nan

Series                     Food production (Index Base: 2004-2006 = 100)  \
Country country_code Year
ARIPO   ARIPO        1985                                            nan
                     1995                                            nan
                     2005                                            nan
                     2010                                            nan
                     2014                                            nan

Series                     Forest cover (% of total land area)  \
Country country_code Year
ARIPO   ARIPO        1985                                  nan
                     1995                                  nan
                     2005                                  nan
                     2010                                  nan
                     2014                                  nan

Series                     Forest cover (thousand hectares)  \
Country country_code Year
ARIPO   ARIPO        1985                               nan
                     1995                               nan
                     2005                               nan
                     2010                               nan
                     2014                               nan

Series                     Grants of patents (number)  \
Country country_code Year
ARIPO   ARIPO        1985                        1.00
                     1995                       64.00
                     2005                      164.00
                     2010                      111.00
                     2014                      254.00

Series                     Gross enrollement ratio - Primary (male)  \
Country country_code Year
ARIPO   ARIPO        1985                                       nan
                     1995                                       nan
                     2005                                       nan
                     2010                                       nan
                     2014                                       nan

Series                     Gross enrollment ratio - Primary (female)  \
Country country_code Year
ARIPO   ARIPO        1985                                        nan
                     1995                                        nan
                     2005                                        nan
                     2010                                        nan
                     2014                                        nan

Series                     Gross enrollment ratio - Secondary (female)  \
Country country_code Year
ARIPO   ARIPO        1985                                          nan
                     1995                                          nan
                     2005                                          nan
                     2010                                          nan
                     2014                                          nan

Series                     Gross enrollment ratio - Secondary (male)  \
Country country_code Year
ARIPO   ARIPO        1985                                        nan
                     1995                                        nan
                     2005                                        nan
                     2010                                        nan
                     2014                                        nan

Series                     Gross enrollment ratio - Tertiary (female)  \
Country country_code Year
ARIPO   ARIPO        1985                                         nan
                     1995                                         nan
                     2005                                         nan
                     2010                                         nan
                     2014                                         nan

Series                     Gross enrollment ratio - Tertiary (male)  \
Country country_code Year
ARIPO   ARIPO        1985                                       nan
                     1995                                       nan
                     2005                                       nan
                     2010                                       nan
                     2014                                       nan

Series                     Health personnel: Dentists (number)  \
Country country_code Year
ARIPO   ARIPO        1985                                  nan
                     1995                                  nan
                     2005                                  nan
                     2010                                  nan
                     2014                                  nan

Series                     Health personnel: Dentists (per 1000 population)  \
Country country_code Year
ARIPO   ARIPO        1985                                               nan
                     1995                                               nan
                     2005                                               nan
                     2010                                               nan
                     2014                                               nan

Series                     Health personnel: Nurses and midwives (number)  \
Country country_code Year
ARIPO   ARIPO        1985                                             nan
                     1995                                             nan
                     2005                                             nan
                     2010                                             nan
                     2014                                             nan

Series                     Health personnel: Nurses and midwives personnel (per 1000 population)  \
Country country_code Year
ARIPO   ARIPO        1985                                                nan
                     1995                                                nan
                     2005                                                nan
                     2010                                                nan
                     2014                                                nan

Series                     Health personnel: Pharmacists (number)  \
Country country_code Year
ARIPO   ARIPO        1985                                     nan
                     1995                                     nan
                     2005                                     nan
                     2010                                     nan
                     2014                                     nan

Series                     Health personnel: Pharmacists (per 1000 population)  \
Country country_code Year
ARIPO   ARIPO        1985                                                nan
                     1995                                                nan
                     2005                                                nan
                     2010                                                nan
                     2014                                                nan

Series                     Health personnel: Physicians (number)  \
Country country_code Year
ARIPO   ARIPO        1985                                    nan
                     1995                                    nan
                     2005                                    nan
                     2010                                    nan
                     2014                                    nan

Series                     Health personnel: Physicians (per 1000 population)  \
Country country_code Year
ARIPO   ARIPO        1985                                                nan
                     1995                                                nan
                     2005                                                nan
                     2010                                                nan
                     2014                                                nan

Series                     Important sites for terrestrial biodiversity protected (% of total sites protected)  \
Country country_code Year
ARIPO   ARIPO        1985                                                nan
                     1995                                                nan
                     2005                                                nan
                     2010                                                nan
                     2014                                                nan

Series                     Index of industrial production: Basic metals (Index base: 2005=100)  \
Country country_code Year
ARIPO   ARIPO        1985                                                nan
                     1995                                                nan
                     2005                                                nan
                     2010                                                nan
                     2014                                                nan

Series                     Index of industrial production: Chemicals, petroleum, rubber and plastic products (Index base: 2005=100)  \
Country country_code Year
ARIPO   ARIPO        1985                                                nan
                     1995                                                nan
                     2005                                                nan
                     2010                                                nan
                     2014                                                nan

Series                     Index of industrial production: Electricity, gas and water (Index base: 2005=100)  \
Country country_code Year
ARIPO   ARIPO        1985                                                nan
                     1995                                                nan
                     2005                                                nan
                     2010                                                nan
                     2014                                                nan

Series                     Index of industrial production: Electricity, gas, steam (Index base: 2005=100)  \
Country country_code Year
ARIPO   ARIPO        1985                                                nan
                     1995                                                nan
                     2005                                                nan
                     2010                                                nan
                     2014                                                nan

Series                     Index of industrial production: Food, beverages and tobacco (Index base: 2005=100)  \
Country country_code Year
ARIPO   ARIPO        1985                                                nan
                     1995                                                nan
                     2005                                                nan
                     2010                                                nan

In [36]:
un_ah.reset_index(inplace=True)

In [37]:
un_ah.head()

Series,Country,country_code,Year,Agricultural production (Index Base: 2004-2006 = 100),All staff compensation as % of total expenditure in public institutions (%),Arable land (% of total land area),Arable land (thousand hectares),"Assault rate per 100,000 population","Asylum seekers, including pending cases (number)",Capital expenditure as % of total expenditure in public institutions (%),Changes in stocks (petajoules),Consumer price index: Food,Consumer price index: General,Current expenditure other than staff compensation as % of total expenditure in public institutions (%),Current health expenditure (% of GDP),Domestic general government health expenditure (% of total government expenditure),Emissions (thousand metric tons of carbon dioxide),Emissions per capita (metric tons of carbon dioxide),Expenditure by level of education: pre-primary (as % of government expenditure),Expenditure by level of education: primary (as % of government expenditure),Expenditure by level of education: secondary (as % of government expenditure),Expenditure by level of education: tertiary (as % of government expenditure),Food production (Index Base: 2004-2006 = 100),Forest cover (% of total land area),Forest cover (thousand hectares),Grants of patents (number),Gross enrollement ratio - Primary (male),Gross enrollment ratio - Primary (female),Gross enrollment ratio - Secondary (female),Gross enrollment ratio - Secondary (male),Gross enrollment ratio - Tertiary (female),Gross enrollment ratio - Tertiary (male),Health personnel: Dentists (number),Health personnel: Dentists (per 1000 population),Health personnel: Nurses and midwives (number),Health personnel: Nurses and midwives personnel (per 1000 population),Health personnel: Pharmacists (number),Health personnel: Pharmacists (per 1000 population),Health personnel: Physicians (number),Health personnel: Physicians (per 1000 population),Important sites for terrestrial biodiversity protected (% of total sites protected),Index of industrial production: Basic metals (Index base: 2005=100),"Index of industrial production: Chemicals, petroleum, rubber and plastic products (Index base: 2005=100)","Index of industrial production: Electricity, gas and water (Index base: 2005=100)","Index of industrial production: Electricity, gas, steam (Index base: 2005=100)","Index of industrial production: Food, beverages and tobacco (Index base: 2005=100)",Index of industrial production: Machinery (Index base: 2005=100),Index of industrial production: Manufacturing (Index base: 2005=100),Index of industrial production: Metal products (Index base: 2005=100),Index of industrial production: Metal products and machinery (Index Base: 2005=100),Index of industrial production: Mining (Index base: 2005=100),Index of industrial production: Mining and manufacturing (Index base: 2005=100),Index of industrial production: Miscellaneous manufacturing industries (Index base: 2005=100),"Index of industrial production: Textiles, wearing apparel, leather, footwear (Index base: 2005=100)","Index of industrial production: Total industry - Mining; manufacturing; electricity, gas and water (Index base: 2005=100)",Index of industrial production: Water and waste management (Index base: 2005=100),"Intentional homicide rates per 100,000",International migrant stock: Both sexes (% total population),International migrant stock: Both sexes (number),International migrant stock: Female (% total Population),International migrant stock: Male (% total Population),"Kidnapping at the national level, rate per 100,000",Land area (thousand hectares),Net imports [Imports - Exports - Bunkers] (petajoules),Net official development assistance received: Bilateral (millions of US dollars),Net official development assistance received: Multilateral (millions of US dollars),Net official development assistance received: Total (as % GNI),Net official development assistance received: Total (millions of US dollars),Other of concern to UNHCR (number),Patents in force (number),Percentage of individuals using the internet,"Percentage of male and female intentional homicide victims, Female","Percentage of male and female intentional homicide victims, Male",Permanent crops (% of total land area),Permanent crops (thousand hectares),Primary energy production (petajoules),Public expenditure on education (% of GDP),Public expenditure on education (% of government expenditure),Pupil-teacher ratio in primary education,Pupil-teacher ratio in secondary education,Pupil-teacher ratio in tertiary education,R & D personnel: Other supporting staff - total (number in full-time equivalent),R & D personnel: Other supporting staff - women (number in full-time equivalent),R & D personnel: Researchers - total (number in full-time equivalent),R & D personnel: Researchers - women (number in full-time equivalent),R & D personnel: Technicians - total (number in full-time equivalent),R & D personnel: Technicians - women (number in full-time equivalent),R & D personnel: Total (number in full-time equivalent),Ratio of girls to boys in primary education,Ratio of girls to boys in secondary education,Ratio of girls to boys in tertiary education,Resident patent filings (per million population),"Robbery at the national level, rate per 100,000 population","Safely managed drinking water sources, rural (Proportion of population with access)","Safely managed drinking water sources, total (Proportion of population with access)","Safely managed drinking water sources, urban (Proportion of population with access)","Safely managed sanitation facilities, rural (Proportion of population with access)","Safely managed sanitation facilities, total (Proportion of population with access)","Safely managed sanitation facilities, urban (Proportion of population with access)","Seats held by women in national parliament, as of February (%)",Students enrolled in primary education (thousands),Students enrolled in secondary education (thousands),Students enrolled in tertiary education (thousands),Supply per capita (gigajoules),Teachers at primary level (thousands),Teachers at secondary level (thousands),Teachers at tertiary level (thousands),"Theft at the national level, rate per 100,000 population","Total Sexual Violence at the national level, rate per 100,000",Total population of concern to UNHCR (number),Total refugees and people in refugee-like situations (number),Total supply (petajoules),Tourism expenditure (millions of US dollars),Tourist/visitor arrivals (thousands)
0,ARIPO,ARIPO,1985,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,1.00,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
1,ARIPO,ARIPO,1995,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,64.00,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
2,ARIPO,ARIPO,2005,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,164.00,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
3,ARIPO,ARIPO,2010,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,111.00,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
4,ARIPO,ARIPO,2014,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,254.00,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,2550.00,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan

In [38]:
un_ah.rename (columns = {
    'Year': 'date',
}, inplace=True)
un_ah.head()

Series,Country,country_code,date,Agricultural production (Index Base: 2004-2006 = 100),All staff compensation as % of total expenditure in public institutions (%),Arable land (% of total land area),Arable land (thousand hectares),"Assault rate per 100,000 population","Asylum seekers, including pending cases (number)",Capital expenditure as % of total expenditure in public institutions (%),Changes in stocks (petajoules),Consumer price index: Food,Consumer price index: General,Current expenditure other than staff compensation as % of total expenditure in public institutions (%),Current health expenditure (% of GDP),Domestic general government health expenditure (% of total government expenditure),Emissions (thousand metric tons of carbon dioxide),Emissions per capita (metric tons of carbon dioxide),Expenditure by level of education: pre-primary (as % of government expenditure),Expenditure by level of education: primary (as % of government expenditure),Expenditure by level of education: secondary (as % of government expenditure),Expenditure by level of education: tertiary (as % of government expenditure),Food production (Index Base: 2004-2006 = 100),Forest cover (% of total land area),Forest cover (thousand hectares),Grants of patents (number),Gross enrollement ratio - Primary (male),Gross enrollment ratio - Primary (female),Gross enrollment ratio - Secondary (female),Gross enrollment ratio - Secondary (male),Gross enrollment ratio - Tertiary (female),Gross enrollment ratio - Tertiary (male),Health personnel: Dentists (number),Health personnel: Dentists (per 1000 population),Health personnel: Nurses and midwives (number),Health personnel: Nurses and midwives personnel (per 1000 population),Health personnel: Pharmacists (number),Health personnel: Pharmacists (per 1000 population),Health personnel: Physicians (number),Health personnel: Physicians (per 1000 population),Important sites for terrestrial biodiversity protected (% of total sites protected),Index of industrial production: Basic metals (Index base: 2005=100),"Index of industrial production: Chemicals, petroleum, rubber and plastic products (Index base: 2005=100)","Index of industrial production: Electricity, gas and water (Index base: 2005=100)","Index of industrial production: Electricity, gas, steam (Index base: 2005=100)","Index of industrial production: Food, beverages and tobacco (Index base: 2005=100)",Index of industrial production: Machinery (Index base: 2005=100),Index of industrial production: Manufacturing (Index base: 2005=100),Index of industrial production: Metal products (Index base: 2005=100),Index of industrial production: Metal products and machinery (Index Base: 2005=100),Index of industrial production: Mining (Index base: 2005=100),Index of industrial production: Mining and manufacturing (Index base: 2005=100),Index of industrial production: Miscellaneous manufacturing industries (Index base: 2005=100),"Index of industrial production: Textiles, wearing apparel, leather, footwear (Index base: 2005=100)","Index of industrial production: Total industry - Mining; manufacturing; electricity, gas and water (Index base: 2005=100)",Index of industrial production: Water and waste management (Index base: 2005=100),"Intentional homicide rates per 100,000",International migrant stock: Both sexes (% total population),International migrant stock: Both sexes (number),International migrant stock: Female (% total Population),International migrant stock: Male (% total Population),"Kidnapping at the national level, rate per 100,000",Land area (thousand hectares),Net imports [Imports - Exports - Bunkers] (petajoules),Net official development assistance received: Bilateral (millions of US dollars),Net official development assistance received: Multilateral (millions of US dollars),Net official development assistance received: Total (as % GNI),Net official development assistance received: Total (millions of US dollars),Other of concern to UNHCR (number),Patents in force (number),Percentage of individuals using the internet,"Percentage of male and female intentional homicide victims, Female","Percentage of male and female intentional homicide victims, Male",Permanent crops (% of total land area),Permanent crops (thousand hectares),Primary energy production (petajoules),Public expenditure on education (% of GDP),Public expenditure on education (% of government expenditure),Pupil-teacher ratio in primary education,Pupil-teacher ratio in secondary education,Pupil-teacher ratio in tertiary education,R & D personnel: Other supporting staff - total (number in full-time equivalent),R & D personnel: Other supporting staff - women (number in full-time equivalent),R & D personnel: Researchers - total (number in full-time equivalent),R & D personnel: Researchers - women (number in full-time equivalent),R & D personnel: Technicians - total (number in full-time equivalent),R & D personnel: Technicians - women (number in full-time equivalent),R & D personnel: Total (number in full-time equivalent),Ratio of girls to boys in primary education,Ratio of girls to boys in secondary education,Ratio of girls to boys in tertiary education,Resident patent filings (per million population),"Robbery at the national level, rate per 100,000 population","Safely managed drinking water sources, rural (Proportion of population with access)","Safely managed drinking water sources, total (Proportion of population with access)","Safely managed drinking water sources, urban (Proportion of population with access)","Safely managed sanitation facilities, rural (Proportion of population with access)","Safely managed sanitation facilities, total (Proportion of population with access)","Safely managed sanitation facilities, urban (Proportion of population with access)","Seats held by women in national parliament, as of February (%)",Students enrolled in primary education (thousands),Students enrolled in secondary education (thousands),Students enrolled in tertiary education (thousands),Supply per capita (gigajoules),Teachers at primary level (thousands),Teachers at secondary level (thousands),Teachers at tertiary level (thousands),"Theft at the national level, rate per 100,000 population","Total Sexual Violence at the national level, rate per 100,000",Total population of concern to UNHCR (number),Total refugees and people in refugee-like situations (number),Total supply (petajoules),Tourism expenditure (millions of US dollars),Tourist/visitor arrivals (thousands)
0,ARIPO,ARIPO,1985,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,1.00,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
1,ARIPO,ARIPO,1995,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,64.00,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
2,ARIPO,ARIPO,2005,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,164.00,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
3,ARIPO,ARIPO,2010,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,111.00,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
4,ARIPO,ARIPO,2014,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,254.00,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,2550.00,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan

In [39]:
un_ah.to_csv ('un_compiled_output.csv', index=False)